name: save_media
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://storyark.eu

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  path: ^1.8.2
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: eu.storyark.save_media
        pluginClass: SaveMediaPlugin
      ios:
        pluginClass: SaveMediaPlugin
